### ISSUE TITLE
DecisionAgent logt SEVERE wanneer topic leeg is.

### ISSUE THREAD

**Issue by rogierpijpers** [MSDA-LifeCycleAgents/brokeragent#17]
Receivebehaviour verwacht XML, maar als de topic leeg is geeft deze een message met de content: "No more messages in this queue." (In: Topic.getOldestMessage() line: 82)

Stacktrace:
jan 18, 2018 4:57:35 PM com.mlaf.hu.decisionagent.behaviour.ReceiveBehaviour handleDirectMessage
SEVERE: Error parsing to object: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.]

**Comment by thijsgelton** [comment]
Aah nu begrijp ik hem. Ik ga het aanpassen.

**Comment by thijsgelton** [comment]
Als het goed is is het zo gefixt. Zou jij het nog willen testen? @rogierpijpers
