### ISSUE TITLE
Config.properties in root

### ISSUE THREAD

**Issue by rogierpijpers** [MSDA-LifeCycleAgents/brokeragent#29]
Het path van config.properties moet naar de root verplaatst worden als het een JAR is geworden. Anders moet je in je eigen project (wanneer je het framework gebruikt) een src/main/resources dir aanmaken voor alleen die file.

**Comment by aacoba** [comment]
Agreed, liep ik gisteren ook al tegenaan.
Ik zit te denken aan /src/main/resources, maar als deze niet gevonden is een fallback op "{user.home}/.config/MLAF/config.properties" ofzo?
Ik denk ook dat het handig is om een default config te parkeren op deze plaats als er daar ook geen config te vinden is.
Hoe denk jij daarover @rogierpijpers ?

**Comment by rogierpijpers** [comment]
Ja t moeilijke is dat je library waarschijnlijk gecompileerd is, dus we moeten heel even testen of hij de config nog kan vinden als hij in de jar included is (het path bestaat in principe niet meer?) maar dan lijkt het me een goed idee om inderdaad te zeggen if config in root not found: default config uit de library. (<- goed idee)
