### ISSUE TITLE
Expliciete commandos meegeven bij message naar BA

### ISSUE THREAD

**Issue by aacoba** [MSDA-LifeCycleAgents/brokeragent#3]

**Comment by thijsgelton** [comment]
@aacoba twijfel ik nog over. Voor nu laat ik het dat de subcriber alleen maar de naam van de topic hoeft te sturen. De brokeragent kijkt dan of de topic al bestaat en zo niet maakt hem dan aan.

**Comment by thijsgelton** [comment]
Note to self: Bij het commando **register** daysToKeepMessages parsen. Bij het commando **retrieve** berichten terug gegeven. Dit kan ook zonder **retrieve** en dat we alleen het commando **register** iets doen en normaal altijd berichten teruggeven.

**Comment by aacoba** [comment]
@thijsgelton Jij had dit toch al geimplementeerd?
