### ISSUE TITLE
Moeten onderstaande methoden niet abstract zijn? (in DecisionAgent)

### ISSUE THREAD

**Issue by rogierpijpers** [MSDA-LifeCycleAgents/brokeragent#31]
/**
     * After unregistering the Sensor Agent this method will be executed. Any other cleaning of left overs by the
     * Sensor Agent should be done in here.
     */
    public void unregisterSensorAgentCallback(AID sensoragent) {

    }

    /**
     * The readings will be saved in memory. In the Measurement of the Instruction Set there is a CircularFifoQueue.
     * The amount of readings in memory is changable in the config.properties. storeReading will be executed after
     * the reading is stored in memory. This method is created so the reading could be stored elsewhere as well.
     */
    public void storeReading(double value, InstructionSet is, Sensor sensor, String measurementId) {

    }

    /**
     * After executing the executePlan method, which is set up using the properties in the Instruction Set, this
     * method will be executed.
     */
    public void executePlanCallback(Plan plan) {

    }

**Comment by aacoba** [comment]
Deze waren eerst abstract, maar ik heb dit in overleg met Thijs weggehaald.
De rede daartoe is dat de "default implementatie"  van niks doen ook prima kan zijn.
Mocht de gebruiker dit willen hij/zij een eigen overerving maken en ze daar implementeren.

**Comment by rogierpijpers** [comment]
Oké dan

**Comment by rogierpijpers** [comment]
@aacoba we hebben net besloten dat t antwoord toch "ja" was (zie Slack).
