### ISSUE TITLE
SensorAgent registreert niet opnieuw als de DA is gerestart

### ISSUE THREAD

**Issue by aacoba** [MSDA-LifeCycleAgents/brokeragent#34]
Als de DA is gerestart en een sensorreading ontvangt van een onbekende SensorAgent antwoord de DA met een DISCONFIRM: "Not registered yet". Als deze binnenkomt bij de SA moet deze zich weer opnieuw registreren.

**Comment by thijsgelton** [comment]
Dit gebeurt al bij de java Sensor Agent. Ook de C++ kant weet hier al vanaf. Toch?

**Comment by rogierpijpers** [comment]
ja de vraag is meer of dit gewenst is... t is niet voor niks dat je de sensor agents opslaat op schijf toch?

**Comment by aacoba** [comment]
Oh, wat trouwens niet goed op te maken is uit mn beschrijving, het opnieuw registreren gebeurt nu (in java iig) niet goed, ik ben hier vandaag tussendoor mee bezig geweest maar heb het nog niet kunnen oplossen, ga er nu weer mee door.

**Comment by thijsgelton** [comment]
Volgens mij hebben we dit al.

**Comment by thijsgelton** [comment]
Fixed
