### ISSUE TITLE
Inkomende berichten opslaan op disk.

### ISSUE THREAD

**Issue by thijsgelton** [MSDA-LifeCycleAgents/brokeragent#6]
@aacoba Dit vraagt waarschijnlijk nog wat onderzoek werk aangezien continue weer opnieuw serialiseren erg 'expensive'.

**Comment by thijsgelton** [comment]
Dit wordt uiteindelijk beperkt tot het serializeren van de HashMap met topics. Het apart opslaan van berichten op disk is nergens voor nodig. Het enige wat wat we willen is dat de Broker Agent bij reboot direct weer gaat bufferen.

**Comment by aacoba** [comment]
@thijsgelton is dit af?
